// <auto-generated />
using System;
using ExpenseTracker.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpenseTracker.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTracker.Domain.Accounts.Entity.PasswordHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PasswordHistory");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Accounts.Entity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PasswordLastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Authorization.Perms.Entity.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ExternalId = new Guid("00edafe3-b047-5980-d0fa-da10f400c1e5"),
                            PermissionDescription = "Admin privileges",
                            PermissionName = "Admin"
                        },
                        new
                        {
                            Id = 2L,
                            ExternalId = new Guid("0918f225-c6f5-a57f-891d-a07ed959163d"),
                            PermissionDescription = "Read user information",
                            PermissionName = "User.Read"
                        },
                        new
                        {
                            Id = 3L,
                            ExternalId = new Guid("1ca8d15b-48f0-e349-5983-a900cfbc7fd7"),
                            PermissionDescription = "Write user information",
                            PermissionName = "User.Write"
                        },
                        new
                        {
                            Id = 4L,
                            ExternalId = new Guid("f149a130-8402-f611-4b56-cfa03d64c3bb"),
                            PermissionDescription = "Delete user information",
                            PermissionName = "User.Delete"
                        },
                        new
                        {
                            Id = 5L,
                            ExternalId = new Guid("3baea94e-bcfa-2629-84c3-651cdc9de0d3"),
                            PermissionDescription = "Read record information",
                            PermissionName = "Record.Read"
                        },
                        new
                        {
                            Id = 6L,
                            ExternalId = new Guid("b1d243fc-d4f7-4ae8-dc1d-d39e70838c1a"),
                            PermissionDescription = "Write record information",
                            PermissionName = "Record.Write"
                        },
                        new
                        {
                            Id = 7L,
                            ExternalId = new Guid("502ee51c-c616-910e-b779-63ba87667975"),
                            PermissionDescription = "Delete record information",
                            PermissionName = "Record.Delete"
                        },
                        new
                        {
                            Id = 8L,
                            ExternalId = new Guid("391e0c54-4528-7134-0753-fa270fb8f203"),
                            PermissionDescription = "Read category information",
                            PermissionName = "Category.Read"
                        },
                        new
                        {
                            Id = 9L,
                            ExternalId = new Guid("56c18f65-ba29-5499-e0ae-ee3329334c83"),
                            PermissionDescription = "Write category information",
                            PermissionName = "Category.Write"
                        },
                        new
                        {
                            Id = 10L,
                            ExternalId = new Guid("9ad393f2-dd00-d1f1-2c1e-07eab87aeb70"),
                            PermissionDescription = "Delete category information",
                            PermissionName = "Category.Delete"
                        },
                        new
                        {
                            Id = 11L,
                            ExternalId = new Guid("c5a9471b-6f8b-cb0b-7700-e3ed16440562"),
                            PermissionDescription = "Read collection information",
                            PermissionName = "Collection.Read"
                        },
                        new
                        {
                            Id = 12L,
                            ExternalId = new Guid("37bfa9f3-7ccf-e5f0-b539-4813004d8a82"),
                            PermissionDescription = "Write collection information",
                            PermissionName = "Collection.Write"
                        },
                        new
                        {
                            Id = 13L,
                            ExternalId = new Guid("18e15ec1-c800-fe03-7525-181cab9808ee"),
                            PermissionDescription = "Delete collection information",
                            PermissionName = "Collection.Delete"
                        });
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Authorization.RolePerms.Entity.RolePermission", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission");

                    b.HasData(
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 2L,
                            ExternalId = new Guid("c9a0fd83-7c68-3b05-b702-4f6a7b61d3ac")
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 3L,
                            ExternalId = new Guid("d15761c8-0eb3-5d39-0d47-ab039a8e424a")
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 4L,
                            ExternalId = new Guid("94c623aa-2a52-fe29-823e-ed27757994af")
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 5L,
                            ExternalId = new Guid("a725ee2c-f14f-1f7f-34a7-8df0e7cb0227")
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 6L,
                            ExternalId = new Guid("8c424643-5a9a-0726-b5ea-217c982fe1b9")
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 7L,
                            ExternalId = new Guid("9a7ac054-05a3-69ad-799f-9bc6dbef753c")
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 8L,
                            ExternalId = new Guid("2cbbf64c-fe68-ecce-2dd7-51d83718c1f1")
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 9L,
                            ExternalId = new Guid("0af91c38-304f-b552-905b-2020455980d7")
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 10L,
                            ExternalId = new Guid("1d871f8e-aad2-7050-1092-5e2d8c6a4117")
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 11L,
                            ExternalId = new Guid("ee9c5384-af1b-2c41-8f19-2290d05a9077")
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 12L,
                            ExternalId = new Guid("f95d305c-11ed-df10-384a-f70592d94a51")
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 13L,
                            ExternalId = new Guid("dfa90665-285c-28d2-504f-1d817deec235")
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 1L,
                            ExternalId = new Guid("4033cabb-30dd-5d7a-9ce8-c2c54dfb8914")
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 2L,
                            ExternalId = new Guid("5e233cc1-ee98-84e7-dd19-434b1d2cbac4")
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 3L,
                            ExternalId = new Guid("23e6bb54-e6a2-d0ba-ca96-5c136d673408")
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 4L,
                            ExternalId = new Guid("c4ad54e3-26ac-45d3-0e6b-9b80b96a3c0d")
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 5L,
                            ExternalId = new Guid("98bab483-e1be-80d9-35ae-18e866b007de")
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 6L,
                            ExternalId = new Guid("d0d1fc9e-45b4-3a10-16a8-e754c3d9ef57")
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 7L,
                            ExternalId = new Guid("12e81ae9-9edb-83df-917c-90df8fe67272")
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 8L,
                            ExternalId = new Guid("fe4bade1-7a77-97c1-94b8-fc63884b57a2")
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 9L,
                            ExternalId = new Guid("40e36409-d2ea-c2fe-2ae3-d766f27dff8e")
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 10L,
                            ExternalId = new Guid("882afe9a-73d9-176e-2574-7157129a8c1c")
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 11L,
                            ExternalId = new Guid("b65dd8d5-097a-5e70-43af-bb6ac596537f")
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 12L,
                            ExternalId = new Guid("9eff1f04-0617-9d7e-7e53-e6d5517fc691")
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 13L,
                            ExternalId = new Guid("a934a83a-be13-03fb-e508-cee05ab9ebe9")
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 2L,
                            ExternalId = new Guid("366f9fdb-bb63-57fd-d1f5-6e1ff41d2f3f")
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 3L,
                            ExternalId = new Guid("25be4811-3723-559b-5a8f-421a6ea8782d")
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 4L,
                            ExternalId = new Guid("4e9a33c9-0396-b818-b464-487334a52367")
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 5L,
                            ExternalId = new Guid("94b5897f-e947-f7c6-2e83-51deca4cd054")
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 6L,
                            ExternalId = new Guid("3fd0f514-7802-cf0e-2d69-11c9d9269d24")
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 7L,
                            ExternalId = new Guid("7f8eee39-2e96-0400-3ebf-10b2a6677f80")
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 8L,
                            ExternalId = new Guid("6a350754-f9cf-ed1d-c4fc-26c721f75596")
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 9L,
                            ExternalId = new Guid("3ebbcbd9-1683-a094-50dd-bf33e07814b3")
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 10L,
                            ExternalId = new Guid("ad32adf2-4a2f-cee3-af77-0521d1ee1e70")
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 11L,
                            ExternalId = new Guid("c66d048b-e67e-fccc-b8cf-a5e410dd2341")
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 12L,
                            ExternalId = new Guid("883e184e-bd6a-6ace-0826-1b976f55b6c1")
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 13L,
                            ExternalId = new Guid("ff513122-1b1f-5c42-e8fe-b4e66acd88dd")
                        });
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Authorization.Tokens.Entity.Token", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<long>("TokenTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("TokenUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("TokenValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("TokenTypeId");

                    b.HasIndex("TokenUserId");

                    b.HasIndex("TokenValue")
                        .IsUnique();

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Authorization.Tokens.Entity.TokenType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimeToLiveInMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("TokenTypeDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("TokenTypeDescription")
                        .IsUnique();

                    b.ToTable("TokenTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ExternalId = new Guid("22446af7-0338-7c34-3be2-9dc71287959e"),
                            TimeToLiveInMinutes = 7200,
                            TokenTypeDescription = "RefreshToken"
                        },
                        new
                        {
                            Id = 2L,
                            ExternalId = new Guid("595fa42b-5a70-f4a0-82a8-c5bd5f6153e8"),
                            TimeToLiveInMinutes = 7200,
                            TokenTypeDescription = "EmailVerificationToken"
                        },
                        new
                        {
                            Id = 3L,
                            ExternalId = new Guid("7c403fa7-89f6-cfbc-d01d-5b3ba3df803c"),
                            TimeToLiveInMinutes = 7200,
                            TokenTypeDescription = "PasswordResetToken"
                        },
                        new
                        {
                            Id = 4L,
                            ExternalId = new Guid("7a0be061-70d4-b8c7-638b-10803d4d67c9"),
                            TimeToLiveInMinutes = 7200,
                            TokenTypeDescription = "AccessToken"
                        });
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Authorization.UserRoles.Entity.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserRoleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ExternalId = new Guid("6da95da4-f60b-5957-70f2-d27af22be28a"),
                            UserRoleName = "System"
                        },
                        new
                        {
                            Id = 2L,
                            ExternalId = new Guid("00edafe3-b047-5980-d0fa-da10f400c1e5"),
                            UserRoleName = "Admin"
                        },
                        new
                        {
                            Id = 3L,
                            ExternalId = new Guid("74e727b0-535f-32c0-5e09-f7de8314c82f"),
                            UserRoleName = "RegularUser"
                        });
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Categories.Entity.TransactionRecordCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("UserId", "CategoryName")
                        .IsUnique();

                    b.ToTable("TransactionRecordCategories");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Collections.Entity.TransactionCollection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("RealBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("UserId", "StartDate");

                    b.HasIndex("UserId", "StartDate", "EndDate", "Description")
                        .IsUnique();

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Email.Entity.EmailDelivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EmailDeliveries");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Records.Entity.TransactionRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("TransactionCategoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("TransactionCollectionId")
                        .HasColumnType("bigint");

                    b.Property<long>("TransactionUserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TransactionValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("TransactionCategoryId");

                    b.HasIndex("TransactionCollectionId");

                    b.HasIndex("TransactionUserId");

                    b.HasIndex("TransactionValue", "TransactionUserId", "TransactionCategoryId")
                        .IsUnique();

                    b.ToTable("TransactionRecords");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Accounts.Entity.PasswordHistory", b =>
                {
                    b.HasOne("ExpenseTracker.Domain.Accounts.Entity.User", "User")
                        .WithOne("PasswordHistory")
                        .HasForeignKey("ExpenseTracker.Domain.Accounts.Entity.PasswordHistory", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Accounts.Entity.User", b =>
                {
                    b.HasOne("ExpenseTracker.Domain.Authorization.UserRoles.Entity.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Authorization.RolePerms.Entity.RolePermission", b =>
                {
                    b.HasOne("ExpenseTracker.Domain.Authorization.Perms.Entity.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Domain.Authorization.UserRoles.Entity.UserRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Authorization.Tokens.Entity.Token", b =>
                {
                    b.HasOne("ExpenseTracker.Domain.Authorization.Tokens.Entity.TokenType", "TokenType")
                        .WithMany("Tokens")
                        .HasForeignKey("TokenTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Domain.Accounts.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("TokenUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TokenType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Categories.Entity.TransactionRecordCategory", b =>
                {
                    b.HasOne("ExpenseTracker.Domain.Accounts.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Collections.Entity.TransactionCollection", b =>
                {
                    b.HasOne("ExpenseTracker.Domain.Accounts.Entity.User", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Email.Entity.EmailDelivery", b =>
                {
                    b.HasOne("ExpenseTracker.Domain.Accounts.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Records.Entity.TransactionRecord", b =>
                {
                    b.HasOne("ExpenseTracker.Domain.Categories.Entity.TransactionRecordCategory", "TransactionCategory")
                        .WithMany()
                        .HasForeignKey("TransactionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Domain.Collections.Entity.TransactionCollection", "TransactionCollection")
                        .WithMany("Records")
                        .HasForeignKey("TransactionCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Domain.Accounts.Entity.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionCategory");

                    b.Navigation("TransactionCollection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Accounts.Entity.User", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("PasswordHistory")
                        .IsRequired();

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Authorization.Perms.Entity.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Authorization.Tokens.Entity.TokenType", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Authorization.UserRoles.Entity.UserRole", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Collections.Entity.TransactionCollection", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
